#fly -t local sp -p website-pipeline -c ci/website-pipeline.yml -v d-repo=dorukakinci/kerimdorukakinci.com -v d-username=xxxx -v d-password=xxxx -v s3-access-key=xxxx -v s3-secret-key=xxxx -v slack-webhook-url=xxxx

slack-hook: &slack-hook
  on_success:
    put: send-slack-notification
    params:
      alert_type: success
  on_failure:
    put: send-slack-notification
    params:
      alert_type: failed
  on_abort:
    put: send-slack-notification
    params:
      alert_type: aborted
  on_error:
    put: send-slack-notification
    params:
      alert_type: errored

resource_types:
- name: s3-sync
  type: registry-image
  source:
    repository: buildo/concourse-s3-sync

- name: key-value
  type: registry-image
  source:
    repository: gstack/keyval-resource

- name: slack-notifications
  type: registry-image
  source:
    repository: arbourd/concourse-slack-alert-resource

resources:
  - name: repo-website
    type: git
    icon: github
    source:
      uri: "https://github.com/DorukAkinci/kerimdorukakinci.com"
      branch: master
      tag_filter: "*"

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: ((d-repo))
      username: ((d-username))
      password: ((d-password))

  - name: s3-website-bucket
    type: s3-sync
    icon: aws
    source:
      bucket: www.kerimdorukakinci.com
      region_name: eu-central-1
      access_key_id: ((s3-access-key))
      secret_access_key: ((s3-secret-key))

  - name: build-info
    type: key-value
    icon: tag

  - name: send-slack-notification
    type: slack-notifications
    icon: slack
    source:
      url: ((slack-webhook-url))

jobs:
  - name: init
    plan:
      - get: repo-website
        trigger: true

      - task: check-latest-tag-version
        config:
          inputs:
            - name: repo-website
          outputs:
            - name: build-info
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine/git }
          run:
            path: sh
            args:
              - -cx
              - |
                cd repo-website
                ls -l
                git tag -l | tail -n 1 > ../build-info/version
                cat ../build-info/version

      - put: build-info
        params:
          directory: build-info

  - name: build
    <<: *slack-hook
    plan:
      - get: repo-website
        passed:
          - init
        trigger: false

      - get: build-info
        passed:
          - init
        trigger: true

      - put: image
        get_params:
          skip_download: true
        params:
          build: repo-website
          tag_file: build-info/version
          tag_as_latest: true

  - name: deploy
    <<: *slack-hook
    plan:
      - get: repo-website
        trigger: true

      - task: remove-unnecessary-files   # workaround for s3 sync issue
        config:
          inputs:
            - name: repo-website
          outputs:
            - name: repo-website
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args:
              - -cx
              - |
                cd repo-website
                ls -l
                rm -rf .git
                rm -rf ci
                rm -f README.md
                rm -f LICENSE
                rm -f Dockerfile
                rm -f .dockerignore
                echo "Final output: " && ls -l

      - put: s3-website-bucket
        get_params:
          skip_download: true
        params:
          source: repo-website
          options:
            - --delete ## is not working for some reason